
(function () {
var scripts = [{"deps":{"./assets/scripts/bird_player":1,"./assets/scripts/bubble_item":5,"./assets/scripts/bubble_item_in_dayscene":2,"./assets/scripts/bubble_item_in_multi":4,"./assets/scripts/enemy moving sharp":3,"./assets/scripts/enemy_wrapper":7,"./assets/scripts/leader":13,"./assets/scripts/light":6,"./assets/scripts/loadgame":8,"./assets/scripts/lose":9,"./assets/scripts/lose_canvas":10,"./assets/scripts/menu":11,"./assets/scripts/missile":14,"./assets/scripts/multi_res_lose":17,"./assets/scripts/multi_res_win":12,"./assets/scripts/pair_game":15,"./assets/scripts/parent":18,"./assets/scripts/player":16,"./assets/scripts/player_day":20,"./assets/scripts/player_multi":23,"./assets/scripts/root":26,"./assets/scripts/rule":19,"./assets/scripts/searchlight":22,"./assets/scripts/section_init":24,"./assets/scripts/sharp":21,"./assets/scripts/sharp_down":27,"./assets/scripts/spider":25,"./assets/scripts/start_scene":29,"./assets/scripts/store":28,"./assets/scripts/arm":31,"./assets/scripts/bird_map_init":30},"path":"preview-scripts/__qc_index__.js"},{"deps":{},"path":"preview-scripts/assets/scripts/bird_player.js"},{"deps":{},"path":"preview-scripts/assets/scripts/bubble_item_in_dayscene.js"},{"deps":{},"path":"preview-scripts/assets/scripts/enemy moving sharp.js"},{"deps":{},"path":"preview-scripts/assets/scripts/bubble_item_in_multi.js"},{"deps":{},"path":"preview-scripts/assets/scripts/bubble_item.js"},{"deps":{},"path":"preview-scripts/assets/scripts/light.js"},{"deps":{},"path":"preview-scripts/assets/scripts/enemy_wrapper.js"},{"deps":{},"path":"preview-scripts/assets/scripts/loadgame.js"},{"deps":{},"path":"preview-scripts/assets/scripts/lose.js"},{"deps":{},"path":"preview-scripts/assets/scripts/lose_canvas.js"},{"deps":{},"path":"preview-scripts/assets/scripts/menu.js"},{"deps":{},"path":"preview-scripts/assets/scripts/multi_res_win.js"},{"deps":{},"path":"preview-scripts/assets/scripts/leader.js"},{"deps":{},"path":"preview-scripts/assets/scripts/missile.js"},{"deps":{},"path":"preview-scripts/assets/scripts/pair_game.js"},{"deps":{},"path":"preview-scripts/assets/scripts/player.js"},{"deps":{},"path":"preview-scripts/assets/scripts/multi_res_lose.js"},{"deps":{},"path":"preview-scripts/assets/scripts/parent.js"},{"deps":{},"path":"preview-scripts/assets/scripts/rule.js"},{"deps":{},"path":"preview-scripts/assets/scripts/player_day.js"},{"deps":{},"path":"preview-scripts/assets/scripts/sharp.js"},{"deps":{},"path":"preview-scripts/assets/scripts/searchlight.js"},{"deps":{},"path":"preview-scripts/assets/scripts/player_multi.js"},{"deps":{},"path":"preview-scripts/assets/scripts/section_init.js"},{"deps":{},"path":"preview-scripts/assets/scripts/spider.js"},{"deps":{},"path":"preview-scripts/assets/scripts/root.js"},{"deps":{},"path":"preview-scripts/assets/scripts/sharp_down.js"},{"deps":{},"path":"preview-scripts/assets/scripts/store.js"},{"deps":{},"path":"preview-scripts/assets/scripts/start_scene.js"},{"deps":{},"path":"preview-scripts/assets/scripts/bird_map_init.js"},{"deps":{},"path":"preview-scripts/assets/scripts/arm.js"}];
var entries = ["preview-scripts/__qc_index__.js"];
var bundleScript = 'preview-scripts/__qc_bundle__.js';

/**
 * Notice: This file can not use ES6 (for IE 11)
 */
var modules = {};
var name2path = {};

// Will generated by module.js plugin
// var scripts = ${scripts};
// var entries = ${entries};
// var bundleScript = ${bundleScript};

if (typeof global === 'undefined') {
    window.global = window;
}

var isJSB = typeof jsb !== 'undefined';

function getXMLHttpRequest () {
    return window.XMLHttpRequest ? new window.XMLHttpRequest() : new ActiveXObject('MSXML2.XMLHTTP');
}

function downloadText(url, callback) {
    if (isJSB) {
        var result = jsb.fileUtils.getStringFromFile(url);
        callback(null, result);
        return;
    }

    var xhr = getXMLHttpRequest(),
        errInfo = 'Load text file failed: ' + url;
    xhr.open('GET', url, true);
    if (xhr.overrideMimeType) xhr.overrideMimeType('text\/plain; charset=utf-8');
    xhr.onload = function () {
        if (xhr.readyState === 4) {
            if (xhr.status === 200 || xhr.status === 0) {
                callback(null, xhr.responseText);
            }
            else {
                callback({status:xhr.status, errorMessage:errInfo + ', status: ' + xhr.status});
            }
        }
        else {
            callback({status:xhr.status, errorMessage:errInfo + '(wrong readyState)'});
        }
    };
    xhr.onerror = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(error)'});
    };
    xhr.ontimeout = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(time out)'});
    };
    xhr.send(null);
};

function loadScript (src, cb) {
    if (typeof require !== 'undefined') {
        require(src);
        return cb();
    }

    // var timer = 'load ' + src;
    // console.time(timer);

    var scriptElement = document.createElement('script');

    function done() {
        // console.timeEnd(timer);
        // deallocation immediate whatever
        scriptElement.remove();
    }

    scriptElement.onload = function () {
        done();
        cb();
    };
    scriptElement.onerror = function () {
        done();
        var error = 'Failed to load ' + src;
        console.error(error);
        cb(new Error(error));
    };
    scriptElement.setAttribute('type','text/javascript');
    scriptElement.setAttribute('charset', 'utf-8');
    scriptElement.setAttribute('src', src);

    document.head.appendChild(scriptElement);
}

function loadScripts (srcs, cb) {
    var n = srcs.length;

    srcs.forEach(function (src) {
        loadScript(src, function () {
            n--;
            if (n === 0) {
                cb();
            }
        });
    })
}

function formatPath (path) {
    let destPath = window.__quick_compile_project__.destPath;
    if (destPath) {
        let prefix = 'preview-scripts';
        if (destPath[destPath.length - 1] === '/') {
            prefix += '/';
        }
        path = path.replace(prefix, destPath);
    }
    return path;
}

window.__quick_compile_project__ = {
    destPath: '',

    registerModule: function (path, module) {
        path = formatPath(path);
        modules[path].module = module;
    },

    registerModuleFunc: function (path, func) {
        path = formatPath(path);
        modules[path].func = func;

        var sections = path.split('/');
        var name = sections[sections.length - 1];
        name = name.replace(/\.(?:js|ts|json)$/i, '');
        name2path[name] = path;
    },

    require: function (request, path) {
        var m, requestScript;

        path = formatPath(path);
        if (path) {
            m = modules[path];
            if (!m) {
                console.warn('Can not find module for path : ' + path);
                return null;
            }
        }

        if (m) {
            let depIndex = m.deps[request];
            // dependence script was excluded
            if (depIndex === -1) {
                return null;
            }
            else {
                requestScript = scripts[ m.deps[request] ];
            }
        }
        
        let requestPath = '';
        if (!requestScript) {
            // search from name2path when request is a dynamic module name
            if (/^[\w- .]*$/.test(request)) {
                requestPath = name2path[request];
            }

            if (!requestPath) {
                if (CC_JSB) {
                    return require(request);
                }
                else {
                    console.warn('Can not find deps [' + request + '] for path : ' + path);
                    return null;
                }
            }
        }
        else {
            requestPath = formatPath(requestScript.path);
        }

        let requestModule = modules[requestPath];
        if (!requestModule) {
            console.warn('Can not find request module for path : ' + requestPath);
            return null;
        }

        if (!requestModule.module && requestModule.func) {
            requestModule.func();
        }

        if (!requestModule.module) {
            console.warn('Can not find requestModule.module for path : ' + path);
            return null;
        }

        return requestModule.module.exports;
    },

    run: function () {
        entries.forEach(function (entry) {
            entry = formatPath(entry);
            var module = modules[entry];
            if (!module.module) {
                module.func();
            }
        });
    },

    load: function (cb) {
        var self = this;

        var srcs = scripts.map(function (script) {
            var path = formatPath(script.path);
            modules[path] = script;

            if (script.mtime) {
                path += ("?mtime=" + script.mtime);
            }
            return path;
        });

        console.time && console.time('load __quick_compile_project__');
        // jsb can not analysis sourcemap, so keep separate files.
        if (bundleScript && !isJSB) {
            downloadText(formatPath(bundleScript), function (err, bundleSource) {
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                if (err) {
                    console.error(err);
                    return;
                }

                let evalTime = 'eval __quick_compile_project__ : ' + srcs.length + ' files';
                console.time && console.time(evalTime);
                var sources = bundleSource.split('\n//------QC-SOURCE-SPLIT------\n');
                for (var i = 0; i < sources.length; i++) {
                    if (sources[i]) {
                        window.eval(sources[i]);
                        // not sure why new Function cannot set breakpoints precisely
                        // new Function(sources[i])()
                    }
                }
                self.run();
                console.timeEnd && console.timeEnd(evalTime);
                cb();
            })
        }
        else {
            loadScripts(srcs, function () {
                self.run();
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                cb();
            });
        }
    }
};

// Polyfill for IE 11
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function () {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
})();
    